apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: umami-pipelinerun-
  namespace: tekton-builds

spec:
  pipelineRef:
    name: umami-pipeline

  workspaces:
    - name: umami
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
    - name: github-ssh-credentials
      secret:
        secretName: github-ssh-credentials
    - name: regcred
      secret:
        secretName: regcred
