apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webhook-website
  namespace: tekton-builds

spec:
  serviceAccountName: tekton-triggers-sa

  triggers:
    - name: webhook-listener
      interceptors:
        - ref:
            name: github
          params:
            - name: eventTypes
              value: [push]

        - ref:
            name: cel
          params:
            - name: filter
              value: "body.ref in ['refs/heads/main', 'refs/heads/develop']"

      bindings:
        - ref: website-trigger-binding

      template:
        ref: website-trigger-template
