apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: website-pipeline
  namespace: tekton-builds

spec:
  params:
    - name: git-repo-url
    - name: git-branch

  workspaces:
    - name: website
    - name: github-ssh-credentials
    - name: regcred

  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: website
        - name: ssh-directory
          workspace: github-ssh-credentials
      params:
        - name: url
          value: $(params.git-repo-url)
        - name: revision
          value: $(params.git-branch)

    - name: semantic-release
      taskRef:
        name: semantic-release
      params:
        - name: github-token-secret
          value: github-token-secret
        - name: github-token-secret-key
          value: GH_TOKEN
      workspaces:
        - name: source
          workspace: website
      runAfter:
        - git-clone

    - name: environment-estimate
      taskRef:
        name: environment-estimate
      params:
        - name: git-branch
          value: $(params.git-branch)
        - name: version
          value: $(tasks.semantic-release.results.version)
      runAfter:
        - semantic-release

    - name: build-container-image
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: website
        - name: dockerconfig
          workspace: regcred
      params:
        - name: BUILDER_IMAGE
          value: gcr.io/kaniko-project/executor
        - name: IMAGE
          value: ghcr.io/kunish/website:$(tasks.environment-estimate.results.image-tag)
      runAfter:
        - environment-estimate
