apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: website-pipeline
  namespace: tekton-builds

spec:
  params:
    - name: git-repo-url

  workspaces:
    - name: website
    - name: github-ssh-credentials
    - name: regcred

  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: website
        - name: ssh-directory
          workspace: github-ssh-credentials
      params:
        - name: url
          value: $(params.git-repo-url)

    - name: build-container-image
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: website
        - name: dockerconfig
          workspace: regcred
      params:
        - name: BUILDER_IMAGE
          value: gcr.io/kaniko-project/executor
        - name: IMAGE
          value: ghcr.io/kunish/website
      runAfter:
        - git-clone
