apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-builds
  namespace: argo-cd

spec:
  project: homelab
  source:
    repoURL: https://github.com/kunish/tekton-builds.git
    targetRevision: HEAD
    path: /
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-builds
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
