apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webhook-website
  namespace: tekton-builds

spec:
  serviceAccountName: tekton-build-bot
  triggers:
    - name: webhook-listener
      interceptors:
        - ref:
            name: github
          params:
            - name: eventTypes
              value: [pull_request]

        - ref:
            name: cel
          params:
            - name: filter
              value: "body.action in ['open', 'synchronize', 'reopened']"

            - name: "filter"
              value: "body.pull_request.merged == false"

      bindings:
        - ref: website-trigger-binding

      template:
        ref: website-trigger-template
