apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: littlelink-trigger-template
  namespace: tekton-builds

spec:
  params:
    - name: git-repo-url
    - name: git-branch

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: littlelink-pipeline-run-
        namespace: tekton-builds
      spec:
        serviceAccountName: tekton-triggers-sa

        pipelineRef:
          name: littlelink-pipeline
        params:
          - name: git-repo-url
            value: $(tt.params.git-repo-url)
          - name: git-branch
            value: $(tt.params.git-branch)

        workspaces:
          - name: littlelink
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 100Mi
                accessModes:
                  - ReadWriteOnce
          - name: github-ssh-credentials
            secret:
              secretName: github-ssh-credentials
          - name: regcred
            secret:
              secretName: regcred
